name: test
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: string
        default: "dev01"

jobs:
  mainjob1:
    steps:
      - name: step1
        run: |
          echo "test1"