name: test
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: string
        default: "dev01"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: step1
        shell: bash
        run: |
          echo 'step1'
      