name: test
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: string
        default: "dev01"

jobs:
  mainjob1:
    uses: ./.github/workflows/template.yaml
    with:
      environment: 'dev'